### ISSUE TITLE
Can not find the module location

### ISSUE THREAD

**Issue by slashmili** [slashmili/alchemist.vim#104]
> copied from https://github.com/slashmili/alchemist.vim/pull/78#issuecomment-319938264

Yes, I have the version in master but still.

I checked the debugging page. I have Elixir 1.5.0 with Erlang 19, and python 2 & 3:

```bash
✗ ~/.vim/plugged/alchemist.vim/alchemist_client -d ./
PING
PONG
END-OF-PING
```

However, even if now I can't reproduce, at the beginning (with same installed versions) it was returning `None`.

```bash
✗ ~/.vim/plugged/alchemist.vim/alchemist_client -d ./
DEFL { "List,flatten", [ context: Elixir, imports: [], aliases: [] ] }
/build/elixir-v1.5.0-src/lib/elixir/lib/list.ex
END-OF-DEFL

✗ ~/.vim/plugged/alchemist.vim/alchemist_client -d ./
DEFLX { "List.flatten", [ context: Elixir, imports: [], aliases: [] ] }
/build/elixir-v1.5.0-src/lib/elixir/lib/list.ex:1
END-OF-DEFLX

✗ ~/.vim/plugged/alchemist.vim/alchemist_client -d ./
DEFL { "CustomModule,foo", [ context: Elixir, imports: [], aliases: [] ] }
/app/lib/eventbox/custom_module.ex
END-OF-DEFL

✗ ~/.vim/plugged/alchemist.vim/alchemist_client -d ./
DEFLX { "CustomModule.foo", [ context: Elixir, imports: [Quickfix], aliases: []] }
/app/lib/eventbox/custom_module.ex:1
END-OF-DEFLX
```

See that there is a `1` instead of a `2`. But then, after I have re-run `mix compile`:

```bash
✗ ~/.vim/plugged/alchemist.vim/alchemist_client -d ./
DEFLX { "CustomModule.foo", [ context: Elixir, imports: [Quickfix], aliases: []]
END-OF-DEFLX
```

No result :(

**Comment by slashmili** [comment]
@waiting-for-dev let's continue here :)

**Comment by waiting-for-dev** [comment]
Yes, it seems more appropriate ;)

**Comment by slashmili** [comment]
@waiting-for-dev thanks for reporting the issue

I'm working on [elixir-sense](https://github.com/slashmili/alchemist.vim/tree/elixir-sense) which solves lots of problem like this.

I keep the issuer open until that new feature is ready

**Comment by waiting-for-dev** [comment]
Hey @slashmili , happy to hear that :) Thanks for your work!

**Comment by slashmili** [comment]
@waiting-for-dev please try the new version

**Comment by waiting-for-dev** [comment]
Hey @slashmili , thanks for the updates :)

Now, I'm getting messages like the following when jumping to any tag:

```bash
alchemist.vim: failed with message error:/home/user/.vim/plugged/alchemist.vim/elixir_sense/lib/elixir_sense/core/ast.ex:16: module HereMyCurrentModuleNamespaceWithoutLastSegment is not loaded and could not be found
E426: tag not found: HereTagNameTryingToJumTo
```

I'm compiling from within a docker container, in an `/app` directory, but I have in `.vimrc`:

```vim
let g:alchemist_compile_basepath = "/app/"
```

**Comment by slashmili** [comment]
@waiting-for-dev did you run `mix compile` before?

I just tried my own docker project and it works 😕 

try to follow this steps: https://github.com/slashmili/alchemist.vim/wiki/Debugging

**Comment by waiting-for-dev** [comment]
> @waiting-for-dev did you run mix compile before?

Yes

> try to follow this steps: https://github.com/slashmili/alchemist.vim/wiki/Debugging

I just tried, with Elixir 1.5.1 and Erlang/OTP 20, and for each example I get the following error message :cry: 

```bash
Traceback (most recent call last):
  File "/home/user/.vim/plugged/alchemist.vim/elixir_sense_client", line 81, in <module>
    main(sys.argv[1:])
  File "/home/user/.vim/plugged/alchemist.vim/elixir_sense_client", line 71, in main
    response = sense.process_command(request, source, line ,column)
  File "/home/user/.vim/plugged/alchemist.vim/elixir_sense.py", line 72, in process_command
    resp_erl_struct = self._send_command(sock, req_erl_struct)
  File "/home/user/.vim/plugged/alchemist.vim/elixir_sense.py", line 260, in _send_command
    raise e
socket.error: [Errno 11] Resource temporarily unavailable
```

**Comment by slashmili** [comment]
@waiting-for-dev enable debug mode and send me the log

open [elixir_sense_client](https://github.com/slashmili/alchemist.vim/blob/master/elixir_sense_client#L6) and enable debug mode

```diff
diff --git a/elixir_sense_client b/elixir_sense_client
index 3a9d62c..53b3a6a 100755
--- a/elixir_sense_client
+++ b/elixir_sense_client
@@ -3,7 +3,7 @@ from __future__ import print_function
 import os, sys, getopt
 from elixir_sense import ElixirSenseClient

-debug = False
+debug = True

 read_stdin = vars(__builtins__).get('raw_input',input)
```

If you are on linux, the logs goes to `syslog`, in Mac it goes to `/tmp/log.log`

**Comment by waiting-for-dev** [comment]
Hmmm... it's strange... I rerun the instructions about debugging and know I get actual output and not that error... :open_mouth: 

Results match with the expected, except for the **Lookup Project's Library** section:


## 1

```bash
~/.vim/plugged/alchemist.vim/elixir_sense_client -d./ -c14 -l3 --request=definition < sample.exs                     
/home/user/projects/clients_webs/eventbox/_build/dev/lib/eventbox/src/Elixir.CustomModule.erl:0%
```
Syslog:

```bash
Sep  5 17:30:31 localhost alchemist_client: project_dir(matched): /home/user/projects/clients_webs/eventbox
Sep  5 17:30:31 localhost alchemist_client: column: 14
Sep  5 17:30:31 localhost alchemist_client: line: 3
Sep  5 17:30:31 localhost alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  5 17:30:31 localhost alchemist_client: Load server settings from: /tmp/alchemist_server/zS2homezS2userzS2projectszS2clients_webszS2eventbox
Sep  5 17:30:31 localhost alchemist_client: Initializing ElixirSense server for environment "dev" (Elixir version 1.5.0)
Sep  5 17:30:31 localhost alchemist_client: Working directory is "/home/user/projects/clients_webs/eventbox"
Sep  5 17:30:31 localhost alchemist_client: ok:localhost:/tmp/elixir-sense-1504624926253959105.sock
Sep  5 17:30:31 localhost alchemist_client: ElixirSense: {'request_id': 1, 'payload': '/home/user/projects/clients_webs/eventbox/_build/dev/lib/eventbox/src/Elixir.CustomModule.erl:-1', 'error': None}
Sep  5 17:30:31 localhost alchemist_client: response:#012/home/user/projects/clients_webs/eventbox/_build/dev/lib/eventbox/src/Elixir.CustomModule.erl:0
```

## 2

```
~/.vim/plugged/alchemist.vim/elixir_sense_client -d./ -c14 -l3 --request=definition < sample.exs                     
/home/user/projects/clients_webs/eventbox/_build/dev/lib/eventbox/src/Elixir.CustomModule.erl:0%
```

Syslog:

```bash
Sep  5 17:31:02 localhost alchemist_client: project_dir(matched): /home/user/projects/clients_webs/eventbox
Sep  5 17:31:02 localhost alchemist_client: column: 14
Sep  5 17:31:02 localhost alchemist_client: line: 3
Sep  5 17:31:02 localhost alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  5 17:31:02 localhost alchemist_client: Load server settings from: /tmp/alchemist_server/zS2homezS2userzS2projectszS2clients_webszS2eventbox
Sep  5 17:31:02 localhost alchemist_client: Initializing ElixirSense server for environment "dev" (Elixir version 1.5.0)
Sep  5 17:31:02 localhost alchemist_client: Working directory is "/home/user/projects/clients_webs/eventbox"
Sep  5 17:31:02 localhost alchemist_client: ok:localhost:/tmp/elixir-sense-1504624926253959105.sock
Sep  5 17:31:02 localhost alchemist_client: ElixirSense: {'request_id': 1, 'payload': '/home/user/projects/clients_webs/eventbox/_build/dev/lib/eventbox/src/Elixir.CustomModule.erl:-1', 'error': None}
Sep  5 17:31:02 localhost alchemist_client: response:#012/home/user/projects/clients_webs/eventbox/_build/dev/lib/eventbox/src/Elixir.CustomModule.erl:0
```

---

Besides, jumping to a tag from vim:

```vim
alchemist.vim: failed with message error:/home/user/.vim/plugged/alchemist.vim/elixir_sense/lib/elixir_sense/core/ast.ex:16: module Eventbox.Domain i
s not loaded and could not be found
E426: tag not found: GetPrebookingDependencies
```

Syslog:

```bash
Sep  5 17:32:47 localhost alchemist_client: project_dir(matched): /home/user/projects/clients_webs/eventbox
Sep  5 17:32:47 localhost alchemist_client: column: 8
Sep  5 17:32:47 localhost alchemist_client: line: 165
Sep  5 17:32:47 localhost alchemist_client: source: [...omited...],
Sep  5 17:32:47 localhost alchemist_client: Load server settings from: /tmp/alchemist_server/zS2homezS2userzS2projectszS2clients_webszS2eventbox
Sep  5 17:32:47 localhost alchemist_client: Initializing ElixirSense server for environment "dev" (Elixir version 1.5.0)
Sep  5 17:32:47 localhost alchemist_client: Working directory is "/home/user/projects/clients_webs/eventbox"
Sep  5 17:32:47 localhost alchemist_client: ok:localhost:/tmp/elixir-sense-1504624926253959105.sock
Sep  5 17:32:47 localhost alchemist_client: response:#012error:/home/user/.vim/plugged/alchemist.vim/elixir_sense/lib/elixir_sense/core/ast.ex:16: module Eventbox.Domain is not loaded and could not be found
```

---

And pressing `K` to go to the documentation:

```vim
Alchemist: No matches for ''!
```

Syslog:

```bash
Sep  5 17:35:31 localhost alchemist_client: project_dir(matched): /home/user/projects/clients_webs/eventbox
Sep  5 17:35:31 localhost alchemist_client: column: 5
Sep  5 17:35:31 localhost alchemist_client: line: 166
Sep  5 17:35:31 localhost alchemist_client: source: [..omited..]
Sep  5 17:35:31 localhost alchemist_client: Load server settings from: /tmp/alchemist_server/zS2homezS2userzS2projectszS2clients_webszS2eventbox
Sep  5 17:35:31 localhost alchemist_client: Initializing ElixirSense server for environment "dev" (Elixir version 1.5.0)
Sep  5 17:35:31 localhost alchemist_client: Working directory is "/home/user/projects/clients_webs/eventbox"
Sep  5 17:35:31 localhost alchemist_client: ok:localhost:/tmp/elixir-sense-1504624926253959105.sock
Sep  5 17:35:32 localhost alchemist_client: response:#012error:/home/user/.vim/plugged/alchemist.vim/elixir_sense/lib/elixir_sense/core/ast.ex:16: module Eventbox.Domain is not loaded and could not be found
```

**Comment by ericdouglas** [comment]
I'm having some issues, here is my debugging results:

> **obs**: Using Erlang/OTP 20 and Elixir 1.5.0

```
➜  alch_debug mix compile
Compiling 2 files (.ex)
Generated alch_debug app
➜  alch_debug cd lib


 
➜  lib ~/.config/nvim/plugged/alchemist.vim/elixir_sense_client -d./ -c1 -l1 --request=definition < sample.exs
Traceback (most recent call last):
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 81, in <module>
    main(sys.argv[1:])
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 71, in main
    response = sense.process_command(request, source, line ,column)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense.py", line 52, in process_command
    req_erl_struct = erl_terms.encode(py_struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 201, in encode
    return FORMAT_VERSION + __encoder_func(struct)(struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 229, in __encode_map
    for k,v in obj.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'



➜  lib ~/.config/nvim/plugged/alchemist.vim/elixir_sense_client -d./ -c6 -l1 --request=definition < sample.exs
Traceback (most recent call last):
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 81, in <module>
    main(sys.argv[1:])
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 71, in main
    response = sense.process_command(request, source, line ,column)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense.py", line 52, in process_command
    req_erl_struct = erl_terms.encode(py_struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 201, in encode
    return FORMAT_VERSION + __encoder_func(struct)(struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 229, in __encode_map
    for k,v in obj.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'



➜  lib ~/.config/nvim/plugged/alchemist.vim/elixir_sense_client -d./ -c6 -l1 --request=docs < sample.exs      
Traceback (most recent call last):
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 81, in <module>
    main(sys.argv[1:])
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 71, in main
    response = sense.process_command(request, source, line ,column)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense.py", line 52, in process_command
    req_erl_struct = erl_terms.encode(py_struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 201, in encode
    return FORMAT_VERSION + __encoder_func(struct)(struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 229, in __encode_map
    for k,v in obj.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'



➜  lib ~/.config/nvim/plugged/alchemist.vim/elixir_sense_client -d./ -c1 -l2 --request=definition < sample.exs
Traceback (most recent call last):
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 81, in <module>
    main(sys.argv[1:])
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 71, in main
    response = sense.process_command(request, source, line ,column)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense.py", line 52, in process_command
    req_erl_struct = erl_terms.encode(py_struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 201, in encode
    return FORMAT_VERSION + __encoder_func(struct)(struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 229, in __encode_map
    for k,v in obj.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'



➜  lib ~/.config/nvim/plugged/alchemist.vim/elixir_sense_client -d./ -c14 -l3 --request=definition < sample.exs
Traceback (most recent call last):
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 81, in <module>
    main(sys.argv[1:])
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense_client", line 71, in main
    response = sense.process_command(request, source, line ,column)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/elixir_sense.py", line 52, in process_command
    req_erl_struct = erl_terms.encode(py_struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 201, in encode
    return FORMAT_VERSION + __encoder_func(struct)(struct)
  File "/home/ericdouglas/.config/nvim/plugged/alchemist.vim/erl_terms.py", line 229, in __encode_map
    for k,v in obj.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
``` 

`syslog`

```
Sep  6 18:32:21 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  6 18:38:21 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:38:21 js alchemist_client: column: 17
Sep  6 18:38:21 js alchemist_client: line: 2
Sep  6 18:38:21 js alchemist_client: source: ustomModule#012CustomModule.foo
Sep  6 18:38:23 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:38:23 js alchemist_client: column: 16
Sep  6 18:38:23 js alchemist_client: line: 2
Sep  6 18:38:23 js alchemist_client: source: ustomModule#012CustomModule.foo
Sep  6 18:38:30 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:38:30 js alchemist_client: column: 17
Sep  6 18:38:30 js alchemist_client: line: 3
Sep  6 18:38:30 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  6 18:38:52 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:38:52 js alchemist_client: column: 4
Sep  6 18:38:52 js alchemist_client: line: 5
Sep  6 18:38:52 js alchemist_client: source: defmodule CustomModule do#012  def foo do#012    :ok#012  end#012end
Sep  6 18:39:46 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:39:46 js alchemist_client: column: 8
Sep  6 18:39:46 js alchemist_client: line: 1
Sep  6 18:39:46 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  6 18:39:51 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:39:51 js alchemist_client: column: 8
Sep  6 18:39:51 js alchemist_client: line: 1
Sep  6 18:39:51 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  6 18:39:56 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:39:56 js alchemist_client: column: 3
Sep  6 18:39:56 js alchemist_client: line: 4
Sep  6 18:39:56 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo#012Li
Sep  6 18:39:56 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:39:56 js alchemist_client: column: 6
Sep  6 18:39:56 js alchemist_client: line: 4
Sep  6 18:39:56 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo#012List.
Sep  6 18:40:20 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:40:20 js alchemist_client: column: 1
Sep  6 18:40:20 js alchemist_client: line: 1
Sep  6 18:40:20 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  6 18:40:44 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:40:44 js alchemist_client: column: 6
Sep  6 18:40:44 js alchemist_client: line: 1
Sep  6 18:40:44 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  6 18:41:01 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:41:01 js alchemist_client: column: 6
Sep  6 18:41:01 js alchemist_client: line: 1
Sep  6 18:41:01 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  6 18:41:14 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:41:14 js alchemist_client: column: 1
Sep  6 18:41:14 js alchemist_client: line: 2
Sep  6 18:41:14 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
Sep  6 18:41:27 js alchemist_client: mix_dir: ['/home/ericdouglas/alch_debug']
Sep  6 18:41:27 js alchemist_client: column: 14
Sep  6 18:41:27 js alchemist_client: line: 3
Sep  6 18:41:27 js alchemist_client: source: Enum.map#012CustomModule#012CustomModule.foo
```

**Comment by slashmili** [comment]
@ericdouglas your problem is related to #110 

If you don't mind I delete your comment here to focus on the main problem

**Comment by slashmili** [comment]
I close this issue for now
