### ISSUE TITLE
Alchemist running in one machine using two users

### ISSUE THREAD

**Issue by slashmili** [slashmili/alchemist.vim#125]
When a vim session run Alchemist.vim for a given project, Alchemist.vim creates a directory in 
`/tmp/alchemist_server/` and keeps the PID of running ElixirSense for that project there.

The problem is if someone tries to open another session vim using different user, would get error like: 
```
Traceback (most recent call last):
  File "./elixir_sense_client", line 81, in <module>
    main(sys.argv[1:])
  File "./elixir_sense_client", line 71, in main
    response = sense.process_command(request, source, line ,column)
  File "/Users/slashmili/.vim/plugged/alchemist.vim/elixir_sense.py", line 53, in process_command
    sock = self.__get_socket()
  File "/Users/slashmili/.vim/plugged/alchemist.vim/elixir_sense.py", line 79, in __get_socket
    self._run_alchemist_server(server_log)
  File "/Users/slashmili/.vim/plugged/alchemist.vim/elixir_sense.py", line 236, in _run_alchemist_server
    log_file = open(server_log, "w")
IOError: [Errno 13] Permission denied: '/tmp/alchemist_server/zS2UserszS2miladzS2.vimzS2pluggedzS2alchemist.vim'
```

We can include the current user id or name in the directory, for example:
user1: `/tmp/alchemist_server_555/`
user2: `/tmp/alchemist_server_556/`

BTW we can also change the name of directory from `alchemist_server` to `elixir_sense`

**Comment by slashmili** [comment]
Fixed
