### ISSUE TITLE
Stacktrace when showing documentation and jumping to definition

### ISSUE THREAD

**Issue by tchoutri** [slashmili/alchemist.vim#137]
1. Elixir/OTP/Python version

Elixir: 1.6.2

OTP: 20.2

Python: 2.7.15

2. Are you using VIM or Neovim? Please provide the version.
NVIM v0.2.2

3. Which plugin are you using:

[ ] basic omnifunc
[ ] YouCompleteMe
[x] deoplete

---

Each time I press `K`, the following stacktrace appears:

```
Traceback (most recent call last):
  File "/home/tchoutri/.config/nvim/.cache/init.vim/.dein/after/../elixir_sense_client", line 81, in <module>
    main(sys.argv[1:])
  File "/home/tchoutri/.config/nvim/.cache/init.vim/.dein/after/../elixir_sense_client", line 71, in main
    response = sense.process_command(request, source, line ,column)
  File "/home/tchoutri/.config/nvim/.cache/init.vim/.dein/elixir_sense.py", line 51, in process_command
    req_erl_struct = erl_terms.encode(py_struct)
  File "/home/tchoutri/.config/nvim/.cache/init.vim/.dein/erl_terms.py", line 212, in encode
    return b'\x83' + _encoder_func(struct)(struct)
  File "/home/tchoutri/.config/nvim/.cache/init.vim/.dein/erl_terms.py", line 241, in _encode_map
    b = b + _encoder_func(k)(k) +  _encoder_func(v)(v)
  File "/home/tchoutri/.config/nvim/.cache/init.vim/.dein/erl_terms.py", line 241, in _encode_map
    b = b + _encoder_func(k)(k) +  _encoder_func(v)(v)
  File "/home/tchoutri/.config/nvim/.cache/init.vim/.dein/erl_terms.py", line 269, in _encode_string
    str_enc = obj.encode('utf-8')
```

and I don't really understand the cause of it.

**Comment by slashmili** [comment]
@tchoutri can follow the [debugging](https://github.com/slashmili/alchemist.vim/wiki/Debugging), set debug flag and run these command on the file you have problem>

```
cd ~/your/project/
/home/tchoutri/.config/nvim/.cache/init.vim/.dein/after/../elixir_sense_client -d./ -c<col_num> -l<line_num> --request=docs <file_name>
```
make sure to change <col_num>, <line_num> and <file_name>

Then please provide the output of the above command the logs in `/tmp/log.log`

**Comment by slashmili** [comment]
I close this issue for now
