### ISSUE TITLE
failed to load deoplete source

### ISSUE THREAD

**Issue by wsdjeg** [slashmili/alchemist.vim#146]
If autocomplete/docs or etc doesn't work for you
before creating issue please check Debugging page and make sure your basic setup works

https://github.com/slashmili/alchemist.vim/wiki/Debugging

and answer these questions:

1. Elixir/OTP/Python version

Elixir: None

OTP: None

Python: Python 3.7.1

2. Are you using VIM or Neovim? Please provide the version.

neovim-qt (master branch daily build)

3. Which pluging are you using:

[ ] basic omnifunc
[ ] YouCompleteMe
[x] deoplete

4. Which steps of Debugging passed?

[ ] Elixir Module definition
[ ] Elixir Function definition
[ ] Elixir Module/Function docs
[ ] Your Project Module definition
[ ] Your Project Function definition

5. Do you have a specific setup? Like Docker and etc

I am so sorry, I do not follow your debug step, just failed to load the deoplete source, the error message is simple

```
[deoplete] Traceback (most recent call last):
  File "C:\Users\Administrator\.cache\vimfiles\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\child.py", line 97, in _add_source
    Source = import_plugin(path, 'source', 'Source')
  File "C:\Users\Administrator\.cache\vimfiles\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\util.py", line 55, in import_plugin
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/Administrator/.cache/vimfiles/repos/github.com/slashmili/alchemist.vim\rplugin\python3\deoplete\sources\alchemist.py", line 4, in <module>
    from elixir_sense import ElixirSenseClient
  File "C:\Users\Administrator\.cache\vimfiles\repos\github.com\slashmili\alchemist.vim\elixir_sense.py", line 9, in <module>
    import syslog
ModuleNotFoundError: No module named 'syslog'
Could not load source: C:/Users/Administrator/.cache/vimfiles/repos/github.com/slashmili/alchemist.vim\rplugin\python3\deoplete\sources\alchemist.py.  Use :messages / see above for error details.
```

This mean the python can not load `syslog` module, I have tried `:py import syslog` and `:py3 import syslog` both failed with  No module named 'syslog'. NOTE, I am using Window os 7.

**Comment by wsdjeg** [comment]
ref links:

https://github.com/cve-search/cve-search/issues/143

https://github.com/soulfx/gmusic-playlist/issues/54

https://github.com/pytest-dev/py/issues/170

https://stackoverflow.com/questions/33074882/importerror-no-module-named-syslog-ansible-edison

**Comment by slashmili** [comment]
I'd say we can `import syslog` in a try catch
