### ISSUE TITLE
Issue with ExDoc and no completion in Deoplete

### ISSUE THREAD

**Issue by kinooyume** [slashmili/alchemist.vim#76]
Hi !
So, I suppose I did something wrong or missed something, but I just follow the doc to install everything, do a `PluginInstall`, `PluginUpdate`.. Then I wanted to try by editing an `.ex` file and I notice that nothing change in deoplete, so I try to use ExDoc by typing `K`, I'v got this message:

```
Traceback (most recent call last):
  File "/home/kiukisas/.config/nvim/plugins/alchemist.vim/after/../alchemist_client", line 77, in <module>
    main(sys.argv[1:])
  File "/home/kiukisas/.config/nvim/plugins/alchemist.vim/after/../alchemist_client", line 69, in main
    print(a.process_command(cmd), end="")
  File "/home/kiukisas/.config/nvim/plugins/alchemist.vim/alchemist.py", line 52, in process_command
    sock = self._connect(connection)
  File "/home/kiukisas/.config/nvim/plugins/alchemist.vim/alchemist.py", line 125, in _connect
    sock.connect(host_port)
```

So.. a `alchemist` connection problem maybe ? 

Also, from the wiki:
```
auto complete and jump to definition only works if your project or newly added file has been compiled
```
I tried again after a `mix compile` in my project but nothing change.. Did I do something wrong ?
I'm on `Arch Linux` and I have `python2.7` and `python3.6` btw.

**Comment by DylanGuedes** [comment]
Hi, exactly the same problem here. When I try to access a doc with `K` I get this weird error, that looks like the connection with alchemist_server isn't working:
```
   1 Traceback (most recent call last):                                                                                                               
   2   File "/home/dguedes/.vim/bundle/alchemist.vim/after/../alchemist_client", line 77, in <module>                                                 
   3     main(sys.argv[1:])                                                                                                                           
   4   File "/home/dguedes/.vim/bundle/alchemist.vim/after/../alchemist_client", line 69, in main                                                     
   5     print(a.process_command(cmd), end="")                                                                                                        
   6   File "/home/dguedes/.vim/bundle/alchemist.vim/alchemist.py", line 52, in process_command                                                       
   7     sock = self._connect(connection)                                                                                                             
   8   File "/home/dguedes/.vim/bundle/alchemist.vim/alchemist.py", line 125, in _connect                                                             
   9     sock.connect(host_port)                                                                                                                      
  10   File "/usr/lib64/python2.7/socket.py", line 228, in meth                                                                                       
  11     return getattr(self._sock,name)(*args)  
```
The plugin is using my Python 2.7, but I also have a few other versions (like 3.0 and 3.5). Using Fedora 25.

**Comment by slashmili** [comment]
Sorry for the late reply

can you troubleshoot the problem like [this issue](https://github.com/slashmili/alchemist.vim/issues/33#issuecomment-271437258)? It's not the exact issue but looks like that

**Comment by DylanGuedes** [comment]
Hi. It creates the file, and the last line of the file says `ok|localhost:43381`. 

Content:
```
warning: module attribute @docmodule was set but never used
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/helpers/capture_io.exs:3

warning: variable "all_loaded" does not exist and is being expanded to "all_loaded()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/helpers/process_commands.exs:15

warning: variable "read_line" does not exist and is being expanded to "read_line()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/server/io.exs:21

warning: variable "schedule_tick" does not exist and is being expanded to "schedule_tick()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:5

warning: variable "idle_expired" does not exist and is being expanded to "idle_expired()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:11

warning: variable "destroy" does not exist and is being expanded to "destroy()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:12

warning: variable "schedule_tick" does not exist and is being expanded to "schedule_tick()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:13

warning: variable "now" does not exist and is being expanded to "now()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:18

warning: variable "now" does not exist and is being expanded to "now()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:30

warning: variable "last_request" does not exist and is being expanded to "last_request()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:30

warning: variable "idle_time" does not exist and is being expanded to "idle_time()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:33

warning: variable "timeout" does not exist and is being expanded to "timeout()", please use parentheses to remove the ambiguity or change the variable name
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:33

warning: module attribute @version was set but never used
  /home/dguedes/.vim/bundle/alchemist.vim/alchemist-server/lib/server.exs:6

ok|localhost:43381
```

**Comment by slashmili** [comment]
@DylanGuedes I might find the issue :) try to fetch master branch again

**Comment by kinooyume** [comment]
Perfect, thank's :banana:

**Comment by DylanGuedes** [comment]
OMG IT WORKED!!! Ty so much
